"""add reserved stock

Revision ID: 14ab99729d7a
Revises: c4964e31814e
Create Date: 2026-09-06 22:51:14.446176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ab99729d7a'
down_revision: Union[str, None] = 'c4964e31814e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reserved_stock', sa.Integer(), nullable=False,server_default='0'
))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'reserved_stock')
    # ### end Alembic commands ###
