"""added suheading to category

Revision ID: 290b3000c73d
Revises: 7289c7996733
Create Date: 2026-07-28 15:36:37.895381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '290b3000c73d'
down_revision: Union[str, None] = '7289c7996733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('subheading', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'subheading')
    # ### end Alembic commands ###
