"""added mpesa details to order schema

Revision ID: 706231149b76
Revises: 85841c2e262f
Create Date: 2026-09-02 10:33:56.403134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706231149b76'
down_revision: Union[str, None] = '85841c2e262f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('checkout_request_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('merchant_request_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('mpesa_receipt_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'mpesa_receipt_number')
    op.drop_column('orders', 'merchant_request_id')
    op.drop_column('orders', 'checkout_request_id')
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###
